apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- extraMounts:
  - containerPath: /dev
    hostPath: /dev
  - containerPath: /var/run/docker.sock
    hostPath: /var/run/docker.sock
  role: control-plane
- role: worker
