apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-registry-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
      - name: custom-app
        image: example.com/custom-app:1.0.0  # Blocked: Image from non-Docker Hub registry
        ports:
        - containerPort: 8080
